### ISSUE TITLE
HTML validator error indicators drift to incorrect locations

### ISSUE THREAD

**Issue by benschwarz** [calibreapp/discuss#17]
![screen-shot-2015-01-13-at-1 27 17-pm](https://cloud.githubusercontent.com/assets/924/5715170/6522958e-9b28-11e4-9480-173ec8889571.png)

As reported by @xzyfer

**Comment by xzyfer** [comment]
Clarification it doesn't drift but is off-by-one. This can result in errors on empty lines. *(same lines as above)*

![screen shot 2015-01-13 at 1 30 08 pm](https://cloud.githubusercontent.com/assets/579928/5715241/e0d64e9a-9b29-11e4-9a61-d2ae39d12afe.png)

**Comment by benschwarz** [comment]
Feature no longer exists. Closing
