### ISSUE TITLE
Budget setting on iPad 

### ISSUE THREAD

**Issue by Gunoksay** [calibreapp/discuss#18]
It won't show most of the time. When it shows it disappears when click and light box stays open so couldn't set it. It was working before.

**Comment by benschwarz** [comment]
Thanks for reporting @Gunoksay, I just tested it on iPhone 6, iOS 8 mobile safari and saw the same result on chrome. I'll get plugged into a simulator when I'm back in the chair and figure it out. 

Right now it looks like a CSS positioning issue
