### ISSUE TITLE
Snapshot sorting is weird

### ISSUE THREAD

**Issue by sawks** [calibreapp/discuss#20]
Added this site last night.

![screenshot 2015-02-17 14 12 42](https://cloud.githubusercontent.com/assets/31912/6222828/3a71d30c-b6af-11e4-8454-ec9dfd51b919.png)

**Comment by benschwarz** [comment]
The worker queues are a bit out of shape right now, I've been reprocessing a whole heap of old snapshot data, which is throwing things out it seems. It should smooth out in the next hour or two… but I'll keep an eye on it to make sure thats the case.

**Comment by benschwarz** [comment]
Happy to call this one solved @sawks ?
