### ISSUE TITLE
[enhancement] Ability to see full URL of each resource on Performance page

### ISSUE THREAD

**Issue by andrewk** [calibreapp/discuss#21]
![screen shot 2015-04-01 at 9 05 56 am](https://cloud.githubusercontent.com/assets/37946/6930459/418337fa-d84f-11e4-8a8a-e7f73f2911e3.png)

In the above screenshot, I have no idea what domain(s) those requests are coming from. 
I know putting the full URL in a `title` attr is a cop-out, but it would be better than nothing.

**Comment by xzyfer** [comment]
This is largely addressed by https://github.com/calibreapp/discuss/issues/27

**Comment by benschwarz** [comment]
I think we can call this one done :hammer:
