### ISSUE TITLE
Subscriptions tab return 500 header

### ISSUE THREAD

**Issue by philgruneich** [calibreapp/discuss#22]
After canceling my organization, I got no success response and now the Subscription tab returns the attached page.

![screen shot 2015-05-27 at 17 51 25](https://cloud.githubusercontent.com/assets/3649691/7847321/1575b89c-0499-11e5-99d6-b9d793f7d673.png)

**Comment by benschwarz** [comment]
I spotted the exception overnight @philgruneich — not sure why it happened yet, but I'll make sure its all clear and confirm for you.

**Comment by philgruneich** [comment]
Thanks, Ben. You can notify me here if you prefer.

**Comment by benschwarz** [comment]
Ok. The exception you saw was 100% dumb and my fault — your account *was* indeed cancelled, and I just removed the organisation. Sorry to see you go, but hopefully one day you'll be back. :haircut:

**Comment by philgruneich** [comment]
Thanks, Ben. I like the service, but it is only me and my tiny blog for now until people decide to care about performance here at my work. Then I'll need a tool such as yours. Thank you!
