### ISSUE TITLE
Can't create a budget greater than my existing maximum

### ISSUE THREAD

**Issue by nickdunn** [calibreapp/discuss#23]
I am mid-way through developing a site and want to set a file size budget that I informally settled on at the start of development. When setting the budget in Calibre I can only drag the slider to the current maximum and no further. I know my file sizes are going to increase over time (e.g. from 25kb to 50kb) so I'd like to be able to set the budget higher.

In short, budget maximums should allow surplus in my opinion.

**Comment by benschwarz** [comment]
@nickdunn I've made a change to allow you to set the budget to 20% more than the maximum value.
Right now, the maximum value is the highest recorded value in the last 30 days. So its that, plus 20%.
