### ISSUE TITLE
Set budgets on a per-site basis rather than per-page

### ISSUE THREAD

**Issue by nickdunn** [calibreapp/discuss#25]
I generally package up and serve the same assets across all pages, therefore I apply the same budgets across all pages of my site. It'd be useful to be able to set the budget globally so that all pages in a site inherit that budget. And then perhaps the ability to override this to increase/restrict specific metrics on a given page.

**Comment by benschwarz** [comment]
Budgets actually are set "site wide", but right now there is no way to do so on a page by page basis.

**Comment by nickdunn** [comment]
Ah brill, thank you. Sorry, first time user taking it all in :-)

**Comment by benschwarz** [comment]
@nickdunn — feedback is awesome, keep it coming
