### ISSUE TITLE
PageSpeed page returning 500 error

### ISSUE THREAD

**Issue by nickdunn** [calibreapp/discuss#26]
I'm unable to view the PageSpeed page for any snapshot, receiving the Rails error:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

https://calibreapp.com/we-are-friday/nuffield-sandbox/snapshots/6/pagespeed

**Comment by nickdunn** [comment]
I keep getting this. It renders the PageSpeed area of the app useless. Is this a known issue, an experimental feature?

**Comment by benschwarz** [comment]
@nickdunn — so sorry, not sure how I entirely missed this issue! 
At the time, there were some issues with retrieving that pagespeed data, which has now been fixed.
