### ISSUE TITLE
[feature request] Sources list

### ISSUE THREAD

**Issue by xzyfer** [calibreapp/discuss#27]
Currently it's possible to see a list of files loaded, but not the full URL (or specifically the domain).

It would be useful to know how many domains are hit to load a page.

**Comment by xzyfer** [comment]
This came up because we are looking at crafting our CSP policy.

**Comment by benschwarz** [comment]
This has been on the roadmap forever — I've just moved it to the "Next up" trello column. 
Thanks for the push @xzyfer !

**Comment by xzyfer** [comment]
\o/

**Comment by benschwarz** [comment]
![lufthansa - calibre 2015-12-28 09-58-29](https://cloud.githubusercontent.com/assets/924/12012475/d5c00338-ad49-11e5-88af-2c7962ed1281.jpg)

Requests panel now shows the filename, domain the request was made to, gzip status, final file size, transfer size (how much the browser downloaded) and the duration that request took. 

Clicking on the arrow will show you the resource on the original server allowing you to make your own deductions about what happened with a given snapshot result. :microscope:

**Comment by xzyfer** [comment]
:heart_eyes:
