### ISSUE TITLE
Show date of snapshot

### ISSUE THREAD

**Issue by godspeedelbow** [calibreapp/discuss#29]
![screen shot 2015-10-21 at 15 00 37](https://cloud.githubusercontent.com/assets/1466424/10637425/ecb3a758-7805-11e5-8b01-9d719b52b6c9.png)

The snapshot # is not that interesting to me, I want to know what date and time the snapshot was taken so that I can check what was deployed at that exact moment. It's impossible to see now in the graph

**Comment by godspeedelbow** [comment]
Actually, pretty interesting because you map the snapshots and not time and because the snapshots don't happen with same frequency, I was confused into thinking that I was looking at a timeline of multiple days (we have 6 snapshots), but actually the first 4 snapshots all happened on the moment.

**Comment by tillkruss** [comment]
+1

**Comment by benschwarz** [comment]
Just following up on this after chatting with @tillkruss — I've moved this up the priority list. 
Want to see this happen. :+1:

**Comment by benschwarz** [comment]
![screen shot 2015-12-28 at 9 19 17 am](https://cloud.githubusercontent.com/assets/924/12012347/169a1dd6-ad44-11e5-8686-ef0d05795381.png)

I deployed this change yesterday — I agree that the snapshot number identifier is definitely secondary information. I'll make further changes in the future that help ground this further. :nail_care:
