### ISSUE TITLE
Be clearer about what browser you use to measure these things

### ISSUE THREAD

**Issue by godspeedelbow** [calibreapp/discuss#31]
So, that users (aka me) don't make assumptions about load times in other browsers. Also, if you're not able in the near future to measure other browsers as well, give me _some_ indication about if/how these results would map to other browsers.

**Comment by benschwarz** [comment]
Good suggestion — where do you think it would make sense to have this information? As part of the snapshot overview? In the docs pages? Both? Somewhere else?
