### ISSUE TITLE
Adding a page is super slow

### ISSUE THREAD

**Issue by godspeedelbow** [calibreapp/discuss#32]
Have to wait for some seconds before I can add another page. Seems like you need do some things asynchronously that now happens during my request/response (but I can also be completely wrong about that).

**Comment by benschwarz** [comment]
Calibre makes some checks to ensure that the site has fully functioning DNS, and checks the page to ensure that it can get a successful response.

You're not the first person to mention this (@godspeedelbow), and I'm definitely sure that you won't be the last. It *is* super slow, and I think its worth making some changes here. I'm going to leave this issue open and open an R&D card to investigate other options.

**Comment by benschwarz** [comment]
There was also a slow query in play — A fix was deployed overnight. Thanks so much for the report.
