### ISSUE TITLE
Your 'handy guide page' about budgets does not exist

### ISSUE THREAD

**Issue by godspeedelbow** [calibreapp/discuss#33]
https://calibreapp.com/peerby/sites/docs/metrics/budgets

Already made this point, but I'd like to see *in the interface* what a budget is.

**Comment by benschwarz** [comment]
@godspeedelbow interestingly — I fixed that help link just before you posted this (which is now deployed). I'd like to improve the dialogue around what metrics and budgets are, which I'll track in #30.

Closing this one—
