### ISSUE TITLE
Users are not validated if they enter a different group

### ISSUE THREAD

**Issue by spiritless** [calibreapp/discuss#34]
If you are logged in and enter a direct url to an existing group you can preview all the sites the group has. Moreover you can add a new site to track . It returns a 500 (check your logs) for the user, but the site is nevertheless added.

**Comment by benschwarz** [comment]
Thanks for the report @spiritless — I was just checking out the situation right now.
I'll update this issue when I've deployed a fix.

**Comment by benschwarz** [comment]
Fix awaiting deploy
