### ISSUE TITLE
[Feature Request] Ability to set user agent and/or device

### ISSUE THREAD

**Issue by jgarber623** [calibreapp/discuss#35]
For the particular site I'm testing, we have separate "desktop" and "mobile" sites at different URLs (`www.` and `m.`). Adding two separate sites in Calibre with the appropriate testing URLs works great, but looking at the snapshots, both appear to be loading the "desktop" site. This makes sense assuming that the testing user agent is a "desktop"-class browser (we're doing UA sniffing and redirecting).

Would it be possible, at the Site level, to set or choose a user agent? Or, at the very least flag a Site as "mobile"…?

Thanks for your time. Calibre is looking really great!

**Comment by benschwarz** [comment]
@jgarber623 Good question, I've wanted to do this for a long time now, and you've nailed the exact perfect use-case — browser sniffing. I'm going to have a think on how we get this through soon, I'll use this issue to track through progress.

**Comment by PaquitoSoft** [comment]
Hey, just wanted to say that I also need this feature.
Os there any way we can help to get it implemented?

Thanks.

**Comment by Russbrown** [comment]
I'd really like this feature too.

**Comment by benschwarz** [comment]
@Russbrown @PaquitoSoft @jgarber623 [Test profiles](https://building.calibreapp.com/announcing-test-profiles-and-budgets-2-0-84667a4e4749#.k8eo5u4vr) just launched 👌

**Comment by jgarber623** [comment]
Thanks, @benschwarz. Congratulations on the feature launch!
