### ISSUE TITLE
Set test location, bandwidth

### ISSUE THREAD

**Issue by techparkopedia** [calibreapp/discuss#36]
Essential to have these basics if this is going to be a more convenient, managed version of webpagetest

Would be great to also see
- repeat view
- zoom on filmstrip thumbnail

**Comment by benschwarz** [comment]
> repeat view

Do you mean the "warm cache" scenario?

> zoom on filmstrip thumbnail 

:+1: Totally want to see that too.

**Comment by benschwarz** [comment]
Setting locations and bandwidth — There's something in the pipeline

**Comment by sanderheilbron** [comment]
+1 for setting locations and bandwidth.

And the possibility to use scripted tests would also be very useful, e.g.:
* set cookies to accept third party requests
* flow view for cached and shared resources between pages

**Comment by pfazzino** [comment]
Yes "repeat view"  == warm/primed cache. Repeat view is the term used on webpagetest but yes, that's exactly what I'm after.

**Comment by benschwarz** [comment]
All this is possible now!
