### ISSUE TITLE
Measure second visit

### ISSUE THREAD

**Issue by PaquitoSoft** [calibreapp/discuss#37]
Hello,

As far as I can tell, every time Calibre visits a web page, it's done with browser clear cache.
It would be great to revisit the same page to get the insights abour how it behaves once the cache has been populated, the same way webpagetest.org does.

Thanks

**Comment by benschwarz** [comment]
@PaquitoSoft Spot on, its a one time view, with caching turned off entirely. 
I agree, warm-cache totally gives you another angle. I want to see that soon too.

**Comment by PaquitoSoft** [comment]
Is there any way I can help?

**Comment by benschwarz** [comment]
@PaquitoSoft I have some plans in this area — Will track it on this issue and reach out for testing / assistance :+1:

**Comment by PaquitoSoft** [comment]
Hi @benschwarz , Is there any new feature that allows this second-visit test?
I've read the [2.0 announcement](https://building.calibreapp.com/announcing-test-profiles-and-budgets-2-0-84667a4e4749#.n6rljydzk) but haven't seen anything about it.

Thanks!

**Comment by benschwarz** [comment]
Hey @paquitosoft, I forgot to leave a comment on this 😅

There currently isn't any plan to do this—but there few other things in the pipeline that will arrive in the next couple of months that'll make this less of an issue. 

Going to stay quiet on the details for now though.
