### ISSUE TITLE
Calibre docs typo

### ISSUE THREAD

**Issue by Allerion** [calibreapp/discuss#39]
Just spotted a typo in your docs.

https://calibreapp.com/docs/site/notifications

2nd paragraph reads:

To set a **budget** for your site, go to your site → Settings → Notifications, and choose the type of notification you'd like to add. Each notification integration will guide you through the process.

**Comment by benschwarz** [comment]
Thanks @Allerion! I was totally thinking about the end goal when I wrote that. 
Fixed, will be deployed momentarily.

**Comment by Allerion** [comment]
No worries. :)

Looks like a fantastic service you're building there.
