### ISSUE TITLE
Pagespeed and embedded basic auth

### ISSUE THREAD

**Issue by gbelorgey** [calibreapp/discuss#41]
We are enforcing our perf budget on our websites in staging, which means they are protected by http basic auth. It's working fine if we embed the credentials in the url, but the pagespeed tab cannot be accessed (500 error apparently)

Is there any way to improve how basic auth is handled ? This is a major use case for us.

**Comment by benschwarz** [comment]
Seeing as we're no longer using page speed (we have our own recommendation system now) — this issue no longer applies. You'll now see perf recommendations no matter what. 🏆
