### ISSUE TITLE
Chrome translation UI is recorded on video (should be disabled)

### ISSUE THREAD

**Issue by onyxmaster** [calibreapp/discuss#42]
https://calibre-screenshots-prod.s3.amazonaws.com/14d1ee6bd687a8f58a2fcee18bdc3321/series/video/20160728051143596.mp4

**Comment by benschwarz** [comment]
Nice catch. I'll have a release out shortly…

**Comment by benschwarz** [comment]
@onyxmaster I pushed a new agent image out this morning with translation disabled 🇷🇺🙈
Thanks for the report 🎉
